### ISSUE TITLE
LIVESTREAMS - Title, keywords.

### ISSUE THREAD

**Issue by Matlemad** [livepeer/livepeer-monorepo#101]
What's the problem?
There is no way to give one livestream a **specific title and/or a number of keywords** in order to make it discoverable on the web. It would be very interesting if I could go on LP landing page, type certain keywords (like "_journalism,Venezuela,politics_")
and discover the livestreams covering that topic live right now.

Current Behaviour.
By now, it's totally on the creator to publicise a livestream through his/her social media.

Possible Solution?
1. Include the **title** and (max 5) **keywords** in the transaction, when I run Livepeer software. is it possible?
2. Being able to type **title** and **keywords** in OBS, perhaps as metadata for the livestream.

Keywords Mindmap.
Once all these titles and keywords are shared live, the most popular trends in topics could show up on a mindmap page somewhere. Every Keyword would get bigger, as more people are covering the same subject at the same time.

Conclusion.
As Josiah explained me, all these features are "external" to protocol's focus right now,
but they can be achieved nonetheless. Only, every new communication to the protocol (like title and keywords) would require a separate transaction.

**Comment by jozanza** [comment]
Yeah this one is a bit tricky since...

1. It requires persistence (the data has to be stored somewhere)
2. This is decentralized project, so we can't use traditional/centralized options.

From conversations I've had with other projects, this could be done in a decentralized manner in a few ways:

| Method                  |                      Pros                      |                                                                                                                                                                                                                                     Cons |
| ----------------------- | :--------------------------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| Smart Contract          | Requires less infrastructure, easiest to build |                                                                                                           Expensive, slow, can't store much. Hard to query. Every new data point we want to add would require a fork or contract upgrade |
| Smart Contracts + IPFS  |          Cheaper, can store more data          |                                                      We'd need to run a service to "pin" stored data otherwise, it would disappear. Users would still need to spend ETH to create a transaction each time they wanted to update anything |
| OrbitDB (built on IPFS) | Cheapest (no txns), fastest, can store plenty  | Requires the most infrastructure: We'd need a pinning service, a signaling service (for peers to discover one another), and a service for locating user db addresses (potentially our own Livepeer OrbitDB, which users could write to?) |

I'm sure there are other options. But these are the ones which are top-of-mind for me in terms of persisting data that should live indefinitely.

Alternatively, for shorter-lived data, we could use a signal server for peers to discover one another and form direct connections where they could send one another specific bits of info (IPFS or WebRTC without the smart contracts -- or perhaps even something like Whisper).

I think @yondonfu might have some thoughts on this technical challenge as well.
