### ISSUE TITLE
Streamline communications by using only one word to refer to the concept of staking

### ISSUE THREAD

**Issue by RaffiSapire** [livepeer/livepeer-monorepo#119]
**What is this discussion about? (required)**
No one in the world has ever staked tokens before us and Steemit. The concept of locking up tokens and earning more is very new, and we need to clearly communicate to people. We use Delegator, Bond, Stake, Token Holder all to refer to the same people with the same needs and motivations. We need to stop using synonyms and stick with one word that describes both the VERB and the NOUN. 

I propose:
Token holders "vote" on "delegates" 
Delegates do the transcoding work

Some changes:
so change "Bond" button to "vote"
change "Delegating" to "voting"
Change Transcoders to "delegates" 

**What do you hope to learn by the end of this discussion? (required)**
At the end of this discussion, I would like for us to agree on one word, update the website, whitepaper, and critical content. 

**Additional context**
I researched other DPoS language and have three high level observations:
1. We have a industry wide communications problem that needs to be fixed  
2. No one uses "stake" no one uses "bond" 
3. Voting is a common concept

Steemit: 
- Delegates / Witnesses,  Steem-Witnesses are the "Transcoders"

Ark: 
- All account holders of Ark can vote 51 delegates. These 51 delegates are allowed to do updates to the database. Delegates are the "Transcoders". 
- Uses the word "vote" for stake. 

Lisk
- LISK holder = token holder is our "delegator" can  vote for a validator 
- Validator is our "transcoder"

**Comment by dob** [comment]
"Validator" seems to be the most universal term I've seen for the elected role in a DPoS system. But yes, industry wide tons of projects use completely different terms. Very confusing for users!

Also keep in mind that our functional role of transcoders is likely evolving to the functional role of orchestrators.

**Comment by jozanza** [comment]
I think we should consistently use these terms:

- **Bond** (verb): to stake tokens to an account
  - other options: stake, delegate, vote
- **Delegate** (noun): an account that may be staked to
  - other options: ???
- **Delegator** (noun): an account that stakes tokens
  - other options: voter, participant, staker
- **Earnings** (noun): stake (LPT) and fees (ETH) gained each round while a delegator is bonded.
  - other options: stake & fees, inflationary rewards & fees
- **Delegating** (noun): the collective actions performed in order to secure the network. This includes bonding, claiming earnings, unbonding, etc.
  - other options: delegation, participating, securing the network, "the delegation game"

Part of the confusion is that every account is technically a delegate in the protocol. You can stake to anyone. It's just not really beneficially to do so. Users should pretty much always bond to transcoders (mainly active ones) in order to get earnings. So delegates should end up being transcoders 99.99% of the time, and the UI should reinforce this.

In practice, I think the best thing to do is tell users either to "bond to an account" or "bond to a transcoder". They should be able to grasp what this means if we are consistent. I'd shy away from using "delegate" and "delegator" unless we're trying to explain something technical about DPoS.

Perhaps "vote" would seem a little more intuitive on the surface, but I think bonding is sufficiently different from voting that it could be misleading to switch over the latter: Why would I need to set a transfer allowance in order to vote? What do we call unbond -- "unvote"? How about partial bonding/unbonding? I'm not sure using the term "vote" will make it any easier for us or users to communicate.

I wouldn't mind coming up with a better term for "delegating" if we can think of one. I think this is where we have the least consistency right now. But rather than focus too much on changing terms, let's focus on consistency and education. I think icons and illustrations can go a long way in this effort. Walls of text is mainly what we give folks right now, and that's always going to make learning a huge challenge.

**Comment by dob** [comment]
Great point about "voting" being different than "delegating"....because "voting" has a different meaning in the potential future governance in our protocol. It's likely that people can submit governance proposal, like parameter changes or smart contract upgrades, and then token holders can "vote" on these proposals (with transcoders being required to vote). So if we use "voting" for transcoders as the term now, this would get confusing later.

**Comment by Randy1Burrell** [comment]
@RaffiSapire, @dob do we have an accord on this. If so can we close this issue?
