### ISSUE TITLE
Register as a Transcoder through Explorer

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#128]
**What's the problem? (required)**

Registering as a transcoder is too hard for some people.

**What's the current behaviour? (required)**

In order to run as a transcoder, a user must run livepeer_cli. 

**Do you have any personal experiences dealing with this problem? (optional)**

Yes, when personally setting up a node, and when helping other people to set up nodes, it becomes clear that unless a user has a strong understanding of command line interfaces, then the process has too much friction.

Also, currently, the TRANSCODING tab in explorer shows _bad news_ and a link to a page with lots of words.

![screenshot_20180622-093918](https://user-images.githubusercontent.com/2212651/41764506-9e7ea644-7601-11e8-816e-9a733b812262.png)

This misses a huge opportunity to get them registered.

**Describe a possible solution you've considered (optional)**

*_To provide users of explorer.livepeer.org the functionality to register as a transcoder using the web interface only._*

This could be done from the TRANSCODING tab in an account view on explorer.

We could offer the mouthwatering prospect of being able to register as a transcoder through the web UI.

**Additional context (optional)**

I am aware that the role of Transcoder requires a certain level of technical skill, in order to run a "high availability" node.

However, we currently have an additional "feature" of the protocol, being the ability to run a node with a campaign to encourage BONDING to the node. See the [list of Transcoding Campaigns in Livepeer's forum](https://forum.livepeer.org/c/transcoders/transcoder-campaign) for these campaigns.

This feature would allow *anyone* to register as a transcoder, start a campaign for LPT holders to BOND to them, and only when they become ACTIVE do they actually have to download and run any software.

It opens up the opportunity for a huge community - the web 3.0 community - to register to try to become active - not just the "command line interface" people.

Technically, all a user could need to be able to register to receive bonded stake is an encrypted UTC keystore file, imported to MetaMask, and then they can start campaigning today. No software install required. No server. No command line interface skills required.

Now, clearly the user would have to run software in order to earn fees, receive rewards, and avoid slashing.

But let's make it easier for people to start campaigning, and if they can be successful in becoming active, their existing bonded stake ought to act as a mechanism to attract people to collaborate in running the node and sharing the reward.

**Comment by jozanza** [comment]
We can make the cli easier, and we can improve the docs. But the transcoder role is not casual and requires a big commitment as well as a solid understanding of Ethereum, devops, and video. And even if you could register from the UI, you'd still have to run the node to actually transcode segments. Not everyone can be a good transcoder -- but that's okay! If you really want to learn how, do that first, then go campaign.

To make transcoding more accessible, **our efforts should focus around educating those interested rather than easily letting them do something they do not fully understand or commit to a role they do not know how to perform**.

The explorer is built for delegators and folks who want visibility into the protocol. It is not a lesser role; it is, however, one that is far better suited for most users. Additionally, the explorer is not a transcoder tool. Transcoders require a very different kind of application and interface. But that's an entirely different discussion and would be a completely separate application.
