### ISSUE TITLE
Generate unmined address

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#135]
**What's the problem? (required)**
Once the slow start is over, we should add a feature to generate unmined addresses for people want to mine for others.

**What's the current behavior? (required)**

**Do you have any personal experiences dealing with this problem? (optional)**

**Describe a possible solution you've considered (optional)**

**Additional context (optional)**

**Comment by dob** [comment]
Couple thoughts on this...

1. I think it's a valuable interface to expose to users, because they are going to ask "How can I get Livepeer token?" and to be able to point them towards a link that helps them is a win.

2. I think it will be short lived. Manually invoking a single txn to mine one other user's account will be tedious and slow. I suspect that most of the LPT will be mined via scripts that submit proofs for many accounts in one tx. It's possible that the whole mine will be over in weeks or a low number of months, so a lot of attention into a custom app for this may not be worth it.

3. Therefore I suspect that a one off tool to be iterated upon quickly, outside of core livepeerjs probably makes more sense. 

4. I think the key thing to show in the app will be the expected # of LPT generated via a txn, the gas cost of submitting the txn, the number of accounts available left to be mined. And maybe some sense of how the # of LPT they'll receive for the same gas price will grow over time so they can evaluate checking back in the future.

**Comment by ericxtang** [comment]
@dob I agree a "single-address-merkle-mine" app will be inefficient.  I think the tool should allow a user to mine for multiple addresses within the same transaction through a deployed smart contract.  Maybe this tool doesn't live in the explorer, but we can link to a post about it.

I agree the explorer should show the information about the merkle mine.  Will create a spec about it and put some bounties there.

**Comment by Randy1Burrell** [comment]
@ericxtang and @dob Could this be marked as resolved?
