### ISSUE TITLE
Why isn't the player also embedded in the explorer?

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#140]
**What is this discussion about? (required)**

The fact that there are two separate web properties to maintain, when it could be just one.

- media.livepeer.org - which shows content being broadcast
- explorer.livepeer.org - which shows what's going on with the protocol

The distinction between the two kinda implies that broadcasting isn't really anything to do with the protocol, which feels a bit narrow-minded.

**What do you hope to learn by the end of this discussion? (required)**

Whether it's a good idea to embed the player into the protocol explorer, and if so, what are the steps required to do it.

**Additional context**

So, of you take a look at [this webpage](https://explorer.livepeer.org/accounts/0x0dDB225031cCB58fF42866f82D907F7766899014/broadcasting), and connect MetaMask to Rinkeby, it shows:

a) Broadcast Funds
b) Broadcast History

I think we're missing an opportunity to also show the livestream content associated with any of these streams *_if they are streaming right now_*.

It could be a really great way to get more traffic going through the explorer, and also a way to use something like www.livepeer.tv to connect viewers in with the protocol.

![screenshot_20180629-015026](https://user-images.githubusercontent.com/2212651/42066093-03791236-7b3f-11e8-8625-7ad74e61b71b.png)

**Comment by chrishobcroft** [comment]
Imagine embedding the player under the BROADCASTING FUNDS section and at the top of the _Job History_ section - if (and only if) the stream is still active.

**Comment by jozanza** [comment]
@chrishobcroft interesting idea.

The livepeer.tv player is a basically a bare-bones example decentralized video application that folks can clone and whitelabel easily. Its purpose is more as an example devs can use as a starting point and  as a dApp anyone can easily deploy to get a shareable link, if they bold enough to try to broadcast in today's world.

The explorer is really about delegation and pretty much serves a totally separate purpose. The task flows are completely unrelated to anything that happens in the player. I'm not really into merging them since I don't see any clear benefit from doing so, and even if we did, it's a pretty big development task.

That being said, it might still be worthwhile to think about ways to crosslink these two apps. If we just want more traffic to flow between them, that should suffice 👍 

Perhaps, in the future, when broadcasting can be easily done from a web browser, we can think about a single "Livepeer dApp" that is a bit broader in its scope! :)

**Comment by dob** [comment]
Echoing Josiah's comments above, the explorer is definitely built and iterated upon to be a protocol explorer - information and actions related to the protocol. And the player hosted at media.livepeer.org is built and iterated upon for displaying media - as an example DApp. While I encourage anyone to fork either, or build a DApp that combines features from protocol interactions with media use cases, each of these tools should stay separate in this context. The explorer should not turn into a portal for every sort of media experience that someone could dream up on top of Livepeer. Closing the issue for bookeeping, but feel free to continue discussing in the comments.
