### ISSUE TITLE
Embedded Player Doesn't Have Logic For Picking CDN Endpoints

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#149]
**Describe the bug (required)**
The main player picks CDN endpoints depending on the channel (if it's crypto.livepeer.tv or livepeer.tv, it uses special CDN endpoints).  The embedded player doesn't do that.

**Expected behavior (required)**
The embedded player just says "stream is currently offline".

**To Reproduce (required)**
1. Embed the player for the livepeer.tv channel into a different website
2. Ensure livepeer.tv is playing video
3. The embedded player will say "stream is currently offline"

**Additional context (optional)**
Take a look at `.env.production`, `packages/player/src/views/Channel/index.js`, `packages/player/src/views/Embed/index.js`.  `Channel` contains the special CDN picking logic, it's not working for `Embed`.  You can see this by looking at the developer console in the browser and seeing where the player is loading the video from.

**Comment by dob** [comment]
I'm guessing this is critical for the Ethereum Magicians livestream embed?

**Comment by ericxtang** [comment]
@dob that's right.  @Randy1Burrell is taking a look.

**Comment by Randy1Burrell** [comment]
@ericxtang How far away is Ethereum Magicians livestream embed? Also what method did you use to embed this player?

**Comment by ericxtang** [comment]
There is a (very discrete) embed button at the bottom-right corner of the player.  The magicians are embedding the player here - https://ethereum-magicians.github.io/berlin-council/livestream/

**Comment by Randy1Burrell** [comment]
@ericxtang and @dob here is what I found:

When I load the page and check my console I see this error:

"Unhandled promise rejection DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document  at createApolloCache (http://localhost:3000/static/js/bundle.js:190302:26)
    at _callee5$ (http://localhost:3000/static/js/bundle.js:190186:25)
    at tryCatch (http://localhost:3000/static/js/bundle.js:11443:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:11677:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:11495:21)
    at step (http://localhost:3000/static/js/bundle.js:11075:30)
    at http://localhost:3000/static/js/bundle.js:11086:13
    at run (http://localhost:3000/static/js/bundle.js:20920:22)
    at http://localhost:3000/static/js/bundle.js:20937:30
    at MutationObserver.flush (http://localhost:3000/static/js/bundle.js:19501:9)"

Some research led me to [this solution](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document).

It seems that when chrome settings enable "third-party scripts cookies are disallowed", then access to localStorage may result in thrown SecurityError exceptions.

The problem here with the embedding is that it is trying to write to the user's browser local storage which chrome doesn't allow by default. Using another browser such as Firefox does not give this error.

**Comment by Randy1Burrell** [comment]
I closed this issue by mistake. The issue has been reopened because I would still like to find a better solution.

**Comment by ericxtang** [comment]
Oh interesting... My chrome seems to have it turned off, but I'm not sure if I did it or it came by default.  But that seems like a different issue we should address.  Can we file a new issue for that, and for now focus on fixing the CDN endpoint bug?

**Comment by Randy1Burrell** [comment]
I am still looking into the CDN bug. The issue I mentioned earlier tricked me for a while into thinking that when embedded the player was not showing in the browser at all. I will file it as an issue soon.

**Comment by rayj00** [comment]
Does it work in all browsers now?

**Comment by Randy1Burrell** [comment]
@rayj00 so far it works in all the browsers that it has been tested with, which are Chromium, Chrome and Firefox on Linux (Ubuntu).
