### ISSUE TITLE
MultiMerkleMine experience not working in Firefox OS X

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#160]
**Describe the bug (required)**
The get token experience isn't working on Firefox OS X. This bug report is from @darkdarkdragon:

macosx, firefox, 
Error: "Subscription field must return Async Iterable. Received: [object Object]"
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gateway.ipfs.io/ipfs/QmbiSa3PSXwRw6aoCRUcEDB4F2c9jvz2UMZJJbyetPA9aY. (Reason: CORS request did not succeed).

**Expected behavior (required)**
MerkleMine should work

**To Reproduce (required)**
1. Open Firefox on OS X
2. Go to https://explorer.livepeer.org/mine
3. Click on Earn LPT

**Device (required):**
 - Firefox OS X

**Comment by dob** [comment]
@darkdarkdragon mentioned that it went away, but now he sees a readablestream error, which I also see...

![screen shot 2018-07-30 at 1 05 04 pm](https://user-images.githubusercontent.com/10389/43411798-406b1810-93f9-11e8-810d-661ee1544c18.png)

**Comment by darkdarkdragon** [comment]
@dob probably what I saw was error on gateway.ipfs.io side - https://explorer.livepeer.org/mine  was not load loading because it was not able to load data from gateway.ipfs.io because of CORS, but now gatewy.ipfs.io returns right CORS headers
what you see now (readablestream error) - it is same I was reporting herer #153 - you need to explicitly enable `ReadableStream` api in Firefox to make it work

**Comment by Randy1Burrell** [comment]
@dob and @darkdarkdragon is this an actual cross browser issue or can we work around it by detecting the user's browser and ask them to enable readable stream?

**Comment by Randy1Burrell** [comment]
[Here is a work around for this issue](https://forum.livepeer.org/t/generating-livepeer-token-using-firefox/339)
