### ISSUE TITLE
multiMerkleMine getting stuck at "Validating Eth Address"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#184]
**Describe the bug (required)**

When using the multiMerkleMine dApp at [this link](https://explorer.livepeer.org/mine), the page sticks at the message saying "Validating Eth Address", and never progresses past this.

For me, this is happening on Ubuntu 18.04.1 on Chromium, Firefox and Brave.

For me, this is working fine using the same Eth Address on MacOS on Brave, but other users are experiencing similar issues on Mac / Chrome.

**Expected behavior (required)**

That the experience of interacting with the multiMerkleMine is working across all operating systems.

**To Reproduce (required)**

0. Log in to MetaMask using either Chromium, Brave or Firefox on Ubuntu
1. Go to https://explorer.livepeer.org/mine 
2. See that it says "Validating Eth Address
3. See that it does not progress past this point... so, no multiMerkleMining for me :(

**Device (required):**
 - Device: Lenovo Thinkpad T480s
 - OS: Ubuntu 18.04.1
 - Browsers: Brave, Chromium, Firefox
 
**Screenshots (optional)**

![screenshot from 2018-08-17 23-51-21](https://user-images.githubusercontent.com/2212651/44291468-d81a9580-a27e-11e8-9fbd-c10afe9766b3.png)
![screenshot from 2018-08-18 00-22-30](https://user-images.githubusercontent.com/2212651/44291469-d81a9580-a27e-11e8-80a6-0b0235c8a907.png)

**Comment by dob** [comment]
May I suggest that we host the account file in the livepeer.org domain? The fact that it's on IPFS means that anyone can always access it for scripting or their own validation, and they don't have to rely on Livepeer in order to generate proofs themselves. But for this mining app, if we can solve this issue by hosting the file, then we should consider doing so.

**Comment by chrishobcroft** [comment]
I've just seen at the bottom of the multiMerkleMine page that the app is known to only work on Windows and Mac.

@Randy1Burrell @RaffiSapire is there a reason Linux was excluded? It seems like an oversight given our focus on incentivising developers? Only people with Macs and Windows can use it?

![screenshot from 2018-08-19 00-16-38](https://user-images.githubusercontent.com/2212651/44303610-2befb200-a345-11e8-9c9e-2ba09e7ba472.png)

**Comment by Randy1Burrell** [comment]
@chrishobcroft I developed MerkleMine dapp and tested on Linux, specifically Ubuntu 18.04. I am not sure how to recreate the problem you are having. Are you running your Ubuntu box in any special environment such as connected to a VPN, a proxy server or any other environment that I didn't mention?

**Comment by chrishobcroft** [comment]
Hmm, how odd. Thanks for following up @Randy1Burrell 

So, I'm running Ubuntu 18.04.1 on a Lenovo Thinkpad T480s, instlled directly on the machine.

The hard drive is encrypted (which shouldn't really cause an issue?).

But not using any VPN or proxy.

**Comment by chrisjgf** [comment]
Same issue here on both Brave and Chrome. Mac OS 10.13.6, Chrome 68.0.3440.106. 

<img width="1520" alt="screen shot 2018-08-19 at 12 00 54" src="https://user-images.githubusercontent.com/19643324/44308151-ad782c00-a3a7-11e8-8d91-4cc08d42fec8.png">

**Comment by chrishobcroft** [comment]
Did someone change something? Now it works on Brave on Ubuntu.

**Comment by oneyesoneno** [comment]
same thing happen to me on chrome
Version 68.0.3440.106 (Official Build) (64-bit)..

I think somewhere like last 3 days i do mining there. At first test, it works. Then i go for 2nd round of mining, then there is error that prevent me to do so. I forgot what is the error, and i just ignore it because i thought it is no big deal, lets try it on another day.

Then today, as mentioned above, some of us experience stuck at "Validating ETH address..."

**Comment by kingjacob** [comment]
Getting the same error, on Brave & Chrome on OSX. Starting some time after 3am PT.

**Comment by ericxtang** [comment]
Fixed. It's because the IPFS gateway sometime disabling cors.  Switching to S3.
