### ISSUE TITLE
Explorer not loading on non web3 enabled browsers

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#185]
**Describe the bug (required)**
The explorer is displaying a blank page (not loading at all) on mobile browsers and non web3 enabled desktop browsers. It is possibly because of this PR, which would throw an exception if web3 isn't injected into the page: https://github.com/livepeer/livepeerjs/pull/164/files

**Expected behavior (required)**
Explorer should load

**To Reproduce (required)**
1. Visit explorer.livepeer.org on mobile safari or brave

**Device (required):**
 - Reproduced on mobile iOS and desktop browsers.
 
**Additional context**
The above referenced PR got Livepeer working within the Mist browser, but I think it's more important to roll it back (or just undo the two line change) and fix this issue, prior to worrying about Mist support.

**Comment by chrishobcroft** [comment]
I don't know if it's related, but I regularly see the explorer not loading in browsers on laptops also.

I can't seem to identify any kind of pattern or cause.

The only potentially relevant detail is that the blank page being loaded is actually some kind of Livepeer content - because it is one of Livepeer's official colours (and not a plain white). So, something is loading, just not everything :/

![screenshot from 2018-08-19 14-36-06](https://user-images.githubusercontent.com/2212651/44308850-4d8c8000-a3bd-11e8-924b-52b171ecaa7a.png)

![livepeer_colors](https://user-images.githubusercontent.com/2212651/44308870-c8559b00-a3bd-11e8-9396-38b3a7af4805.png)

**Comment by chrishobcroft** [comment]
I also experience this:

1. Load the mine page in Chromium (https://explorer.livepeer.org/mine)

2. Witness that the page doesn't load fully - only a blank page

3. Press F12 to view developer console

4. Page loads.

Does this have anything to do with it?
