### ISSUE TITLE
Broadcaster Community Crowdfunding

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#229]
**What's the user story?**

As a **Broadcaster** in Livepeer's network, I would like to make it _really_ easy for my **Community** to support my activities.

**What's the current behaviour?**

As a **Broadcaster**, I can fund _my own_ account with ETH - see _View as_ **_Broadcaster_** screenshot below:

![image](https://user-images.githubusercontent.com/2212651/46299360-79487b80-c5a1-11e8-8ed4-71b79f7a19da.png)

As **Community**, I **_cannot_** fund a **Broadcaster's** account - see _View as_ **_Community_** screenshot below:

![image](https://user-images.githubusercontent.com/2212651/46300675-9d598c00-c5a4-11e8-8775-ef1525a7ae1d.png)

**Do you have any personal experiences dealing with this problem?**

Sometimes my broadcasting funds were zero on Rinkeby, and I think @ericxtang had to deposit some fake-Ether himself.

There was no way for the **Community** to come together to _support the **Broadcaster**_ financially.

**Describe a possible solution you've considered**

I suggest we make it possible for **anyone to be able to fund a broadcaster directly** into their DEPOSITED ETH in Livepeer's protocol.

![image](https://user-images.githubusercontent.com/2212651/46301693-5b7e1500-c5a7-11e8-89dc-864c5345e71e.png)

It can act as a way to open up the funding for the flow of content on Livepeer. It could even be re-branded / re-packaged as some kind of widget to embed on my webpage to fund me as a broadcaster on Livepeer. Kind like Patreon.

It's also a very rudimentary **"pay-as-you-go" implementation for content**. Like a _community-funded juke-box_.

And if we could get broadcaster funding controllable by an Aragon DAO, then this would be interesting as a way to directly democratically manage funding for the media. But I digress.

**Additional context (optional)**

> _It's not much yet, but it's a start I suppose._

Below is a recent snapshot of the TOTAL BROADCASTING FUNDS for Livepeer, as presented by the wonderful [Supermax](https://www.supermax.cool/livepeer):

![image](https://user-images.githubusercontent.com/2212651/46299276-4ef6be00-c5a1-11e8-9bd3-cf6b1a1ea159.png)

This is effectively the pool of resource for **Broadcasters** to pay the costs (plus a margin) of:

1. **Orchestrators** and **Transcoders** for Transcoding segments, and
2. **Delegators** who receive a share of a **Transcoder's** fees (in ETH), for bonding their stake to the network.

So, that's pretty much everybody. It's essentially the oil of Livepeer's financial machine. It's not much yet, but it's a start I suppose.

I don't know whether this might be possible just through some stuff on the front-end @adamsoffer? Or would it need some new smart contract code @yondonfu? What do you think?

In some ways it can loosely be like "bonding" to your favourite **Broadcaster** in a much more simplistic way, of course. We could even show a top 15, and launch something in the forum - **Broadcasters** / **Broadcaster** Campaigns - where **Community** can build funds to broadcast. @RaffiSapire what do you think?

And it feels like it could be a nice way to help feed the protocol. @dob @f1l1b0x what do you think?

And if you think about it, the **Broadcasters** in this current context might actually be more like **_Developers_** who need to pay the Transcoders - so in many ways this can represent _a way to crowdfund development of Livepeer_.

**Comment by saskakol** [comment]
There is already a tipping option in the player. It shows up when you have Web3 unlocked. It lets you tip ETH to the broadcaster’s address. Is that the sort of functionality you are looking for, or would it need to be expanded somehow? Are you thinking of having this in the Explorer or the Player?

EDIT: Or are you thinking of this as an expansion to the network rather than one of the packages in this repo?

**Comment by j0sh** [comment]
@iSasFTW the tip goes towards the broadcaster's account balance, but doesn't actually go into the deposit that's meant for broadcasting. Perhaps we could change the tipping behavior so that it's applied towards the deposited balance. This might require a protocol change, since deposits can apparently only be made towards yourself.

https://github.com/livepeer/protocol/blob/815b87be879cc508f370590675decd0b46385e46/contracts/jobs/JobsManager.sol#L200-L209

**Comment by RaffiSapire** [comment]
The goal of this work is functionality that a video application should
build to support a broadcaster, but out of scope of building out Livepeer's
open source infrastructure
ᐧ

**Comment by chrishobcroft** [comment]
Thanks @j0sh for clarification.

@iSasFTW I'm thinking of this in a broader context of some sort of product for Broadcasters - which an embryonic concept in my mind.

@RaffiSapire thanks for chiming in. I don't mind who builds.

**Comment by yondonfu** [comment]
If the protocol supported [broadcaster designated signers](https://github.com/livepeer/LIPs/issues/13), a group of individuals could pool funds via a smart contract that deposits funds on behalf of contract users with a separately designated account that actually operates the broadcaster node.

**Comment by f1l1b0x** [comment]
the idea that the broadcast node is also the content creator is flawed. 
in v2 a single broadcast node will handle many streams and might be just a gateway for content creators on all kinds of platforms. 
It is better if tipping functions being direct between the artist and the viewer and it does not need to get squeezed into the livepeer protocol since anyone could always build a tipping button for his community.

**Comment by dob** [comment]
I think the discussion and brainstorming around this is great inspiration for the type of broadcaster apps that can be built on the platform. But as Randy is working hard to keep the issues in the LivepeerJS repo organized, and focused on the core platform rather than applications, perhaps a better place for the discussion is in the project board for "project proposals", which is designated exactly for this type of brainstorming and collaboration? https://github.com/livepeer/project-management/projects/1

**Comment by Randy1Burrell** [comment]
Closing this, we can always reopen if needed. Thanks @dob for the suggestion.
