### ISSUE TITLE
Player initial flow logic after introducing `/current.m3u8` endpoint

### ISSUE THREAD

**Issue by ya7ya** [livepeer/livepeer-monorepo#236]
**What is this discussion about? (required)**
the `livepeerjs/player` currently uses the `sdk` along with the broadcaster ETH address to get the latest Job and pull that manifest. with the introduction of `current.m3u8`, and #227 , we don't need the blockchain lookup.

**What do you hope to learn by the end of this discussion? (required)**
We should be able to decide whether we want to take the `sdk` blockchain call out of the initial flow? and figure out if `/streamId` endpoint should be available publicly.

**Additional context**
The current player needs the sdk call to get the manifestID and other metadata related to the job. current.m3u8 doesn't provide us with the streamId so we're not able to populate the fields properly. but we can play the manifest without a problem.

**Comment by dob** [comment]
I know this is a little late, as it relates to `current.m3u8` since we already have the functionality, but since this is a Discussion thread...

I'm not sure how useful `current` is in the context of many streams per ingest node. Imagine you're building a scaled video application - you likely run one ingest node for many of your users streams concurrently - so the concept of requesting the `current` one is a little meaningless at best, and unpredictable at worst. 

So I get that in our iterative development flow it may be temporarily useful to have the concept of `current`, for debugging and serving a single stream/node, but I would be careful about too many changes to additional components or designs that rely on it being useful for the long term.

**Comment by j0sh** [comment]
Yeah, `/current.m3u8` was built to accommodate our immediate needs, and the [original ticket](https://github.com/livepeer/go-livepeer/issues/556) explicitly says that the behavior becomes undefined once we support multiple streams per broadcaster.

Once we support multiple streams, we'd need another querying mechanism entirely, since the old blockchain lookup wouldn't work either.

> We should be able to decide whether we want to take the sdk blockchain call out of the initial flow? and figure out if /streamId endpoint should be available publicly.

Since we can't really rely on the blockchain to give accurate information on which manifest is currently active, we should remove it as a top-level endpoint.

It'd still be good to retain the ability in the SDK to retrieve a list of jobs belonging to the account, any of which may be active at the moment. By parameterizing the query, a user could limit the result set to the most recently created job, if they still needed the information for other reasons.

**Comment by Randy1Burrell** [comment]
@ya7ya was this solved by last week's PR #243?

**Comment by ya7ya** [comment]
yes,, this can be closed, `current.m3u8` is used with `/Channels/local` route.

**Comment by j0sh** [comment]
What if the node is not on localhost but still wants to play the current stream? For example, the Livepeer media player accessing `livepeer.tv` .

**Comment by Randy1Burrell** [comment]
@ya7ya what @j0sh said?

**Comment by ya7ya** [comment]
@Randy1Burrell @j0sh right now, `current.m3u8` only works with the `local` mode.
