### ISSUE TITLE
Confusion on fee share vs reward cut

### ISSUE THREAD

**Issue by dtkong** [livepeer/livepeer-monorepo#254]
**What's the problem? (required)**
> Reward Cut: Reward Cut is the percent of the newly minted token that the Transcoder keeps from the round’s inflation distribution. The remainder gets distributed across all bonded nodes in proportion to how much you bond relative to others. For example if this is 20%, that means that if a Transcoder were to receive 100 LPT in block reward and their “reward Cut” were 20%, they would keep 20 LPT and distribute remaining 80%, or 80 LPT
> Fee share: Fee share is how much the delegator receives of the Price/segment. For example if Fee Share is 25%, If a transcoder were to charge 100WEI in fees per segment, they would pay 25WEI to the bonded nodes

In my limited experience as a user, it's confusing that 
Reward Cut is the % that goes to Transcoder
and Fee share is % that goes to delegator

I think it'd be more clear if the direction of the incentives go the same way. 
+ note, it's also not immediately apparent that there's an info tool tip that explains the term on hover. 

**What's the current behavior? (required)**

One can see this "lost in translation" happening in the transcoder campaigns for instance. Instead of stating 5% reward cut, transcoders might say "95% of the rewards go to you!" 

**Describe a possible solution you've considered (optional)**

It's not as concise, but specifically labeling the terms and having the incentives flow one direction. I would suggest towards the Transcoder as it's the Transcoder view on the explorer.
Transcoder Reward Cut (%) and Transcoder Fee Cut (%)

**Comment by dob** [comment]
Yes, this has been confusing users since day 1. The reasoning, and starting point was that 0%, 0% would be the default - a transcoder keeps 0% of your stake rewards (which is supposed to be in proportion to stake), and a transcoder shares 0% of the fees (since they are the one doing the work). 

One thing to note is that the underlying protocol itself will likely not change - so the data structures in the smart contracts and input arguments to the transactions to set and read these values will stay the same - but this doesn't mean the UX and language can't be updated for the end user.

**Comment by adamsoffer** [comment]
The new explorer uses the language "Share Cut" and "Fee Cut" to avoid confusion.
