### ISSUE TITLE
Add [max] button to transfer allowance and bonding

### ISSUE THREAD

**Issue by dtkong** [livepeer/livepeer-monorepo#255]
**What's the problem? (required)**
I want all my LPT to be bonded, but I don't know off-hand exactly how much LPT I have to X decimal points.

Interface also shows varying levels of decimal points in diff places which can cause some minor dust issues.

**What's the current behavior? (required)**
Different behavior during transfer allowance and bonding, but at certain points, there isn't clear display to reference and have to switch screens. 

**Do you have any personal experiences dealing with this problem? (optional)**
I typed in the max I saw in the interface, but after successful bonding, it looks like there was some dust remaining that wasn't bonded. 

**Describe a possible solution you've considered (optional)**
I'd like there to be a max button that pulls the total LPT I have in an account for the transfer and bonding approval. 
I would also like to see my LPT balance at all times. 

**Additional context (optional)**
Add any other context or screenshots about the enhancement or feature request here.

<img width="928" alt="screen shot 2018-11-08 at 12 04 12 pm" src="https://user-images.githubusercontent.com/769311/48218022-87cb4500-e34e-11e8-83ad-f358612555a2.png">

**Comment by Randy1Burrell** [comment]
@dtkong I like this idea, but I am not sure if this feature is really needed because the user's LPT balance is displayed to them with 18 decimal places precision when they are bonding. Copy and pasting the value displayed gives max. While, it would be easier to just click a button, I would like to avoid a situation where adding a button confuses new users or a user mistakenly clicks on max and bonds all their tokens when that was not the intention.

Let me know what you think.

**Comment by adamsoffer** [comment]
The new explorer allow you to stake your max balance by clicking "balance". 
![image](https://user-images.githubusercontent.com/555740/73901726-a8d85980-4861-11ea-9b3b-68e65daee538.png)
