### ISSUE TITLE
Helping Delegators to Manage Unbonding Locks within the Explorer 

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#261]
**What is this discussion about? (required)**
This discussion is about giving users the ability to manage their UnbondingLocks from the AccountDelegating page in the explorer.

**What do you hope to learn by the end of this discussion? (required)**
Given that unbonding (whether partially or fully) creates an UnbondingLock each time a Delegator unbonds, that Delegators can use to withdraw their tokens when a certain period has passed (currently 7 days). I am proposing to add a Pending UnbondingLocks section within the AccountDelegators page in the explorer. This section will only appear when Delegators have pending unbonding locks. This will help Delegators in the following ways:

1. Whenever their lock(s) are able to be withdrawn/rebonded they can do so with a single click of a button.
2. They will no longer need to interact directly with the BondingManager's smart contract and will be able to avoid the hassle/confusion and have a much better UX.
3. Less time spent searching or trying to find out what happened to their tokens when they try to unbond.
4. Creates less confusion because now the explorer will be able to tell Delegators when their tokens can be withdrawn.
5. All the history can be shown in the accounts overview page.

**Additional context**
When a Delegator unbonds and the tx is processed we can do either of two things:

1. Redirect to the AccountDelegating page where the Unboding Locks section will appear.
2. Show a pop out notification about where pending UnbondingLocks can be viewed.

I like the second solution better.

I am proposing to put this within the AccountDelegating page because that is where all the information regarding a Delegator's tokens can be viewed.

**Comment by dob** [comment]
I like this very much from a technical perspective. Putting the unbonding locks on the account delegation page with the options to:

* rebond
* withdraw (when available)

will be very helpful.

From a product/communication perspective, this is definitely a new and confusing concept for users though. What is an unbonding lock? Why do they have to manage it? Perhaps rather than use that term and telling users to "Manage their unbonding locks", I could imagine something a little more context oriented in the UX. For example:

You unbonded 100 LPT on 11/16. It will be available to withdraw on 11/23 | Rebond 100 LPT
You unbonded 250 LPT on 11/1. It is available to withdraw now | Withdraw 250 LPT | Rebond 250 LPT

(Just a suggestion for discussion - not a full UX design!)

There is also a small detail to understand, which is that I think if the user has fully unbonded, he no longer has an active transcoder he's bonded towards, so the rebond() method actually doesn't work and instead they have to call "rebondFromUnbonded" and specify an input transcoder. I'm not sure if the UX needs to support this as a first iteration, but I wanted to mention it.
