### ISSUE TITLE
Missed Reward Call column showing incorrect data

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#281]
**Describe the bug (required)**
In The Graph implementation that is currently sitting on staging, the Missed Reward Call column shows how many reward calls were missed in the last 30 rounds. The numbers seem very incorrect.

For example if you look at the second node, 0x4ff.. you'll see that he clearly called reward at least 27 of the last 30 rounds (observed by looking at their recent txns in the Overview tab of their profile page, except the column reports he missed 16 out of 30. Many of the others look way off too.

**Expected behavior (required)**
The numbers should correctly show how many reward calls were missed in the last 30 rounds.

**To Reproduce (required)**
1. Go to http://explorer-staging.livepeer.org.s3-website-us-east-1.amazonaws.com/transcoders and observe 16/30 missed calls for the node 0x4ff088...
2. Go to http://explorer-staging.livepeer.org.s3-website-us-east-1.amazonaws.com/accounts/0x4ff088ac5422f994486663ff903b040692797168/overview and count the number of reward calls in the last 30 days. You'll see far fewer than 16.

**Device (required):**
 - Macbook Pro, OS X, Brave

**Additional context (optional)**

**Note, this is a blocking bug, as it would be very unfair to inaccurately report on this number as it would negatively effect transcoders who have put a lot of work into running reliably.**

**Comment by adamsoffer** [comment]
@dob Ah yes good spot. Luckily, this is not an issue with the indexer, but rather a frontend bug. If you [query our subgraph for that specific transcoder](https://thegraph.livepeer.org/subgraphs/name/livepeer?query=%7B%0A%20%20transcoders(where%3A%7Bid%3A%220x4ff088ac5422f994486663ff903b040692797168%22%7D)%20%7B%0A%20%20%20%20rewards%20%7B%0A%20%20%20%20%20%20rewardTokens%0A%20%20%20%20%20%20round%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) you should see 5 missed calls over the last 30 rounds, not 16, which matches up with what I'm observing in that transcoder's recent transactions on its profile page.

The issue lies [here](https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/components/TranscoderCard/index.js#L33). We're filtering all the transcoder's missed calls and then slicing the last 30 rounds. The order of operations should be the other way around: slice the last 30 rounds _and then_ filter the missed calls. @Randy1Burrell do you want to just include this fix in your [open PR](https://github.com/livepeer/livepeerjs/pull/280)? Should look like this:

```javascript
if (rewards) {
  missedCalls = rewards.slice(-30).filter(reward => reward.rewardTokens === null).length
}
```

**Comment by Randy1Burrell** [comment]
@adamsoffer I will include it in my PR.

**Comment by Randy1Burrell** [comment]
[Here is the commit](https://github.com/livepeer/livepeerjs/pull/280/commits/4be59cebbc2b3d260da2371facf4c34beba2894d). @dob and @adamsoffer Gonna push this to staging and you tell me if anything else is wrong.

**Comment by dob** [comment]
Looks good to me!

**Comment by Randy1Burrell** [comment]
Great!!
