### ISSUE TITLE
Build Unbonding Form View 

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#295]
**What's the problem? (required)**
I am unable to unbond partially within the explorer.

**What's the current behavior? (required)**
Clicking on unbond gives a metamask popup prompting you to unbond all of your stake.

**Do you have any personal experiences dealing with this problem? (optional)**
Yes, I have found that you can change the gas price in MetaMask but that's about it. An unbonding form should be built that is similar to the current bonding form. The difference would be how it operates. 

**Describe a possible solution you've considered (optional)**
When a user click unbond and unbonding modal containing an form should popup that guides the user to unbond partially or fully unbond. Hence, an unbonding form view is needed to give the user the ability to interact with the unbonding form mentioned in issue #294. 

**Additional context (optional)**
The view should look similar and operate similar to the current bonding form in the explorer with the difference being that it has an option to unbond partially or unbond fully. [Here is the bonding view's  code](https://github.com/livepeer/livepeerjs/tree/master/packages/explorer/src/views/Bond), which is example code of how the unbonding form view code may look and work.

### **Bonding Form**
![image](https://user-images.githubusercontent.com/10135939/50197960-8c085c00-0317-11e9-90aa-2b8b23e03c28.png)

### **Unbonding Form Example**
![image](https://user-images.githubusercontent.com/10135939/50198028-d1c52480-0317-11e9-96a7-8e720d2d867b.png)

**_Note:_** The styling of the unbonding form component should be the same/similar to the bonding form.

Please see [partial unbonding](https://preview.uxpin.com/889b8e76042300f53aef82b29ff22567ebf6bcbf#/pages/98491956/simulate/sitemap?mode=i) and [fully unbonding](https://preview.uxpin.com/e339740dc9aa5862f4c7c88a3f1b6edfc1556b3f#/pages/98379007/simulate/sitemap?mode=i) for a walk through of the mock ups and user flow of how partial/fully unbonding should operate.

**Comment by RaffiSapire** [comment]
Note: when you click unbond all LPT, the amount should be autofilled. When you click unbond partial LPT, the amount should be editable.

**Comment by RaffiSapire** [comment]
@Randy1Burrell  please note I have adjusted the text for the unbonding popup, and this should be consistent everywhere. I have updated mockups. 

Unbonding Definition. Unbonding allows you to withdraw your token by releasing the token from the deposit with its Transcoder.
Unbonding Period. Once you unbond, it takes 7 days (the unbonding period) in order to be able to withdraw your token.
Amount. You may unbond ALL or a PARTIAL amount of LPT. Enter the amount of LPT you wish to unbond in the box below.
View Unbonding Transactions. View unbonding transactions on the Staking page. Go to Account -> Staking and scroll to "Pending LPT."
Multiple Unbonding Transactions. Each time you Unbond a partial amount of token, a transaction is created and must be withdrawn or rebonded separately.
Change your mind? If you have initiated the Unbonding process but wish to rebond your LPT, you do not need to wait for the period to end. Go to the Staking page on your account and click "Rebond."
