### ISSUE TITLE
Explorer - Unbond fails if rewards aren't claimed

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#35]
#### New Issue Checklist

- [x ] I made sure the issue observed is not already reported by searching on Github under https://github.com/livepeer/livepeerjs/issues
- [ x] I have filled out all relevant sections of this issue template

#### Expected Behavior
I click "unbond" in the transcoder view of the protocol explorer on the transcoder that I am currently delegated to. I expect to be unbonded.
...

#### Current Behavior
I receive an error pop up with the failed transaction receipt metadata, indicating that all my gas was used and the transaction failed.
...

#### Possible Solution
I likely am not up to date on my fee claiming with this metamask based account. Perhaps the unbond transaction needs to kick off the round-by-round fee claiming under the hood before it can invoke the unbond() transaction.

#### Steps to Reproduce (for bugs)
1. Visit the transcoder view of the explorer.
2. Bond towards an active transcoder.
3. Wait 24 hours (perhaps this could be as short as wait 100+ rounds or ~8 hours).
4. Refresh the transcoder view. 
5. Unbond from the transcoder.
6. Sign the transaction with metamask. Wait for the failure window to pop up.

#### Context

...

#### Your Environment

Chrome on OS X

#### Console Output

```
GraphQL error: {
  "receipt": {
    "blockHash": "0xef23d6b32a43d2246a0542fbc3e5b0ad1237c0af4199eb36135bfb5a70223953",
    "blockNumber": "f3df6",
    "contractAddress": null,
    "cumulativeGasUsed": "911a",
    "from": "0x5a4a992c26cba8459ec0d77f4c66216d2a8fd18f",
    "gasUsed": "911a",
    "logs": [],
    "logsBloom": "0x000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000",
    "status": "0x0",
    "to": "0x4bb510aaf8acaa7879a0a4650cf21731bb8b072c",
    "transactionHash": "0x96214299cb9c9b6f93903c1af32d5aed08f257f7c689b0354033666d5faa8fd5",
    "transactionIndex": "0"
  },
  "transaction": {
...
```

**Comment by jozanza** [comment]
That is actually the expected behavior at the moment. But it's definitely not great. Mostly, it's a result of creating something shippable for the "bonding experience" within the time frame of a single sprint. In the future, the features will be a little more thought-through by doing some basic amount of UX design/research before moving into the implementation.

As I go through the exercise of analyzing task flows for this particular interaction, as well as some others, I'll be able to come up with some enhanced patterns for dealing with, and ideally preventing, transaction failures such as this.

I'll leave this issue open until we feel like the experience in production is satisfactory. Your idea about prompting the user to claim their outstanding fees is definitely noted. Feel free to comment with any others you might have! 👍

**Comment by jozanza** [comment]
The UI now proactively warns a user about this. Further UX improvements can always be made, but I will close this issue so those improvements can be discussed in their own separate issues.
