### ISSUE TITLE
User flow for "Withdraw Stake", "Withdraw Fees", "Claim Earnings"

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#39]
@jozanza has created the initial user flow for "withdraw stake", "withdraw fees", and "claim earnings".

[Delegation.pdf](https://github.com/livepeer/livepeerjs/files/1761225/Delegation.pdf)

Let's all provide some feedback.

**Comment by ericxtang** [comment]
I like where this is going.

I think the round initialization indicator is good, and the claim earnings message makes sense.  For the withdraw buttons, what do you think about making them always visible, but in an "active" or "inactive" state?  In addition to that, users might need explanations on "why" the buttons are inactive.

**Comment by yondonfu** [comment]
I like the task flow diagrams! I think they might even be helpful to post as developer resources in addition to being used for designing the explorer UX.

Nav Bar
- I like the indicator next to “My Account” to signal to the user that there is some action that she should take by clicking the “My Account” button to navigate to the “Overview” page. Perhaps the color of the indicator should be something else besides green though since green is also associated with success for the round initialized indicator - maybe yellow? 

Overview
- I wonder if the ETH display component should exactly mimic the LPT display component and offer the “Transfer” option instead of the “Deposit” option and move the “Deposit” action into the “Broadcasting” page since depositing ETH is only meaningful in a broadcasting context
- Just noting that for the main net version, there will be no ETH or LPT faucet so we’ll have to take out the “Request” option in the ETH and LPT components

Claim Earnings
- In the scenario where the user has a number of unclaimed rounds and the “Claim Earnings” button is visible, perhaps it would be helpful for the user to also display the actual amounts of claimable rewards and fees for those unclaimed rounds

Task Flows
- Bond
    - For the approval only your LPT balance needs to be greater than or equal to the approval amount. The ERC20 approval function doesn’t know anything about bonding
    - You don’t necessarily need to approve an amount to bond IF you already have a bonded amount, but do not have a delegate (i.e. you unbonded from your previous transcoder and have not withdrawn your stake). In this case, you can bond with a provied amount of 0 to just delegate your current bonded amount to a new transcoder

**Comment by jozanza** [comment]
Since these actions are now available in the explorer UI, I'm going to close this thread, and we can follow up with more specific issues concerning the usability of these interactions if we want to discuss enhancements or bugs.
