### ISSUE TITLE
Player - Local stream support

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#4]
A very common workflow when trying to run a Livepeer node is to try to broadcast a stream, and then view it played back. Right now the docs point the user to play it back in the web player hosted at media.livepeer.org/player.html. This player will attempt to pull the stream from the local node if it's running, and if not, fall back to the CDN. It makes for a very nice first experience, even if the user hasn't sync'ed the entire blockchain and is just running in offchain mode, or trying to set up a private network.

We need to be able to maintain this experience, whether it's through the new hosted web player, or the new, upcoming explorer, or even just a separate local web player dapp that is distributed with Livepeer.

**Comment by jozanza** [comment]
Folks can now run this project locally and configure the "stream root url" is now via `.env` files (https://github.com/livepeer/livepeerjs/commit/56d7c3f835de8db8450f0b0a24e9fbcb13112334). You can read more documentation [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env). I've been using it extensively for the past few days to isolate various loading/error states, which is difficult to do when requesting playlists from testnet because of current instability.
