### ISSUE TITLE
token transfer error

### ISSUE THREAD

**Issue by Yksnod** [livepeer/livepeer-monorepo#404]
**Describe the bug (required)**
After adding new tokens to my already bonded MEW address i could not see my bonded tokens any more in the explorer. I also couldn't unbond or add the new tokens to the existing bond address. I can see the new tokens in the explorer but i am not able to do anything, can't bond. After transferring the new tokens to an other MEW and wait for 24hrs i still can not see the  already existing bonded tokens.

**Expected behavior (required)**
I would like to see my existing tokens back and able to unbond so i can add the newly bought tokens to the bonding process 

**To Reproduce (required)**
1. Go to '0x237C3Ae54596bb3295FcbF5c02641cA66C7A6F10'

**Device (required):**
 - macbook pro
 - MacOs Mojave
 - Chrome
 - ?
 
**Screenshots (optional)**
0x237C3Ae54596bb3295FcbF5c02641cA66C7A6F10

<img width="1234" alt="Screenshot 2019-05-07 at 18 56 31" src="https://user-images.githubusercontent.com/50344106/57318121-e012b200-70f9-11e9-9923-fad383571e79.png">

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by ericxtang** [comment]
Thanks for filing this issue.  

To clarify - you don't have to unbond in order to bond your new tokens.  You can simply move the new tokens to the same Eth address you used to bond your tokens, and click "bond" again.  You can do this for the same transcoder, or a new transcoder.

If you unbond, there will be an unbonding period of around 7 days before you can withdraw the unbonded token.

**Comment by gavinly** [comment]
Hi @ericxtang! It may be worth updating the unbonding period in the wiki: https://github.com/livepeer/wiki/wiki/Delegating
