### ISSUE TITLE
CANT UN BOND, SO SLOW, NO PROFIT

### ISSUE THREAD

**Issue by mooleshacat** [livepeer/livepeer-monorepo#407]
I am unable to unbond my stake and redelegate because I only get 0.01% fees

Site so slow it is unusable

How I get my LPT unbonded?

Surprised this system even works... I assume it does, right?

**Comment by mooleshacat** [comment]
I cant even claim the 0.09 LPT I got over the last few days...

The calculators are all wrong about profit whgen you have to use other transcoder

Dumb system as soon I get out I am dumping this garbage and getting my BTC back if I can

If there was no github to contact anyone this would be so horrible I would label it as a scam.

All withdraw buttons blanked out and disabled. when click "claim" for 0.09 LPT it does nothing I have to refresh the page.

**Comment by ericxtang** [comment]
Thanks for reporting the bug @leshacat.  A lot of times, the explorer is slow due to the fact that it's loading data from the Ethereum blockchain.  We are working on solutions to solve this issue.

If you are familiar with your way around mycrypto, you can use the contract ABI directly to call "unbond".  Or you can also use [onclickdapp](https://forum.livepeer.org/t/how-to-partially-unbound-without-any-cli-commands/485).

**Comment by adamsoffer** [comment]
Closing since the classic explorer is no longer maintained.
