### ISSUE TITLE
Again..Can't Bond - No Icon for any Transcoder

### ISSUE THREAD

**Issue by jvanlan** [livepeer/livepeer-monorepo#422]
The Jing video explained all of the "Requirements"

Describe the bug (required)
There is not an icon to bond on the transcoder screen

Expected behavior (required)
I expected to see the "Bond" icon on each transcoder

To Reproduce (required)
See Jing Video: https://www.screencast.com/t/jJHyn2jZlpT

Go to https://explorer.livepeer.org/transcoders
-No "Bond" icon on any transcoder
Click on any Transcoder and there is also no icon to Bond at the top for any Transcoder.

Device (required):

Device: PC
OS: Win 10
Browser Chrome & Firefox tested
Version 74.0.3729.131
Screenshots (optional)
If applicable, add screenshots to help explain your problem. https://www.screencast.com/t/jJHyn2jZlpT

**Comment by ericxtang** [comment]
Thanks for filing the issue @jvanlan.  Is this a consistent problem?

**Comment by Randy1Burrell** [comment]
@jvanlan In the video I noticed that your wallet is not connected to the explorer. You need to first give the app permission to access your wallet before the bond buttons show up. Otherwise you might be able to access the accounts page through searching for an address but not able to access any features that involves using your wallet.

**Comment by adamsoffer** [comment]
Closing since the old explorer is no longer supported.
