### ISSUE TITLE
Livepeer Subgraph returns wrong values on rewardCup and feeShare fields

### ISSUE THREAD

**Issue by cristianmalfesi** [livepeer/livepeer-monorepo#426]
**Describe the bug (required)**
On Livepeer subgraph, the query of active transcoders returns wrong values sometimes on rewardCut and feeShare fields. If I compare these values between the subgraph and Explorer (explorer.livepeer.org), some values from the subgraph are wrong.

**Expected behavior (required)**
Compare Transcoder values of rewardCut and feeShare fields from the subgraph with the values reported by explorer.livepeer.org/transcoders and should have the same numbers.

**To Reproduce (required)**
- I run this query on Livepeer Subgraph:
https://thegraph.com/explorer/subgraph/graphprotocol/livepeer
Query:
`{
  transcoders(first: 30, where:{active:true}) {
    id
    active
    status
    rewardCut
    feeShare
    pendingRewardCut
    pendingFeeShare
    totalStake
  }
}`
2- Compare the query result with the transcoders values from the list of https://explorer.livepeer.org/trasncoders.
3- Some values are different and on subgraph side some are cero.

 
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/22707133/61071970-b707e980-a3e8-11e9-9fa7-6076ac86ddea.png)

**Comment by adamsoffer** [comment]
Hey @chm1975 - great spot! I looked into this and found the issue.

We're getting `rewardCut` by calling `getTranscoder()` inside the `transcoderUpdated` mapping. However, when a transcoder registers for the first time, `rewardCut` is naturally “0”.  Since a transcoder’s `pendingRewardCut` only goes into effect the following round, we need to set a transcoder's `rewardCut` inside the `newRound` mapping.

This issue doesn't currently affect the explorer because the transcoder card component uses the pendingRewardCut value, and the transcoding profile view isn’t yet using subgraph data. This is probably why no one noticed this before.

I'll make sure to include this fix in [this long-running PR](https://github.com/livepeer/livepeerjs/pull/325).

Thank you!

**Comment by cristianmalfesi** [comment]
Good to know @adamsoffer ! Thanks for the quick feedback.
