### ISSUE TITLE
ETH fees not credited

### ISSUE THREAD

**Issue by ajukjose** [livepeer/livepeer-monorepo#443]
Even though transcoders have fees sharing why arent the accounts credited with ETH? I've tried bonding to different transcoders But I still don't get ETH fees.  Looking for some help

**Comment by adamsoffer** [comment]
Hey @ajukjose - the amount of fees in ETH you can expect depends on how much video is flowing through the network at any given moment and the amount LPT you have staked. Right now the network is in an alpha state and there's not much video being broadcasted into it which is why you're not seeing any fees. The usage so far in the alpha release has been people streaming events, conferences, and meetups. The upcoming "Streamflow" release takes the alpha from functional proof of concept, to actually scalable, cost-effective, and reliable enough to start targeting applications and video platforms to use the network. When this happens, expect to start seeing broadcasting fees in ETH make its way to your account.
