### ISSUE TITLE
Claim not received!

### ISSUE THREAD

**Issue by diogo-alcantara** [livepeer/livepeer-monorepo#464]
Hi, I have claimed 1.07 LPT:

https://etherscan.io/tx/0xfb4285777454e2c44e73b7b143230b94a063117191501371518f7535f7ff60eb

But I have not received.

**Comment by shishangx** [comment]
me too:
https://etherscan.io/tx/0x522dcad22fec29e0c2ed2efc4e6f7b520d68fe6f71147d8257eaaa7b122daae5

**Comment by adamsoffer** [comment]
Claiming LPT will not withdraw rewards into your wallet. To withdraw rewards into your wallet, submit an unstake transaction, wait the 7 day unbonding period, then withdraw them into your wallet.

Side note, manually claiming has been removed from the explorer UI since rewards are automatically claimed and it's no longer necessary.
