### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by nicolasburtey** [livepeer/livepeer-monorepo#48]
Is there any statistics regarding how many people access https://media.livepeer.org?

I think of something like Google Analytics (GA) that could be used to monitor basic metrics such as : 
- how many people connect to https://media.livepeer.org
- how long do they watch videos
- how many "not found" type of event users see on average

Ideally, the access to the statistics could be open for anyone to follow the growth of the network

Note: I'm just citing GA but I'm not sure this would be the right tool. Some decentralized solution could be a better fit if any exists. Interestingly, ethereum.org use GA.

**Comment by dob** [comment]
Yes, definitely would be helpful to have insight into these. When we've discussed before it's always come down to user privacy and decentralized ideals vs the benefits that these would provide.

Since we're hosting the site and running nodes in order to serve this content, it seems reasonable that analytics could be included. I'd feel better about it if the code that activated the tracking would only execute if the site were being run on media.livepeer.org. If someone downloaded the open source code to run the DApp locally, then it would be free from tracking.

**Comment by dob** [comment]
I wanted to re-open this discussion with a proposal:

**Add Google Analytics to the media.livepeer.org hosted pages**

The benefits of having visibility into user statistics and behavior are clear. But it also comes with certain potential downsides with regards to centralized tracking being potentially at odds with the philosophical aspects of decentralization, and putting users in control of their own data. Here's how I would propose balancing these:

1. The google analytics tracker only is embedded if the page is served at media.livepeer.org, which is a domain that Livepeer Inc hosts and serves, as well as pays for. 

2. Since the media.livepeer.org site is really just an open source DApp, we have clear instructions in the Github README about how to build a version of the player that anyone can host themselves. This version would be free from the tracker.

I'm not sure whether the tracker would get included via the build process, or inserted at runtime based upon the domain, but I think that's an implementation detail.

**What to track?**

Well, I think that Google gives quite a bit out of the box. Let's start with trying to determine what we can from the available data. If there are custom integrations involved in order to glean statistics that aren't otherwise available, let's track those requests as separate issues since they may require additional build. cc @RaffiSapire @chrishobcroft @jozanza.

**Comment by RaffiSapire** [comment]
Spoke w Josiah about setting up analytics today and that was focused on livepeer tv, not media.livepeer.org. This is because we're hoping to answer the question, what role does livestreaming our own content play in helping us achieve our goals during the snowmelt phase. Wondering if we can use analytics to get to a point where we can show that, for example, livepeertv has x% level of engagement, and is increasing x% MoM, or lptv drives x% of distribution registrants, or x% of traffic to discord. 

As next step, @jozanza Josiah is going to chat with @chrishobcroft this week to get analytics set up to track number of views, bounce rate, where they are coming from to start, and from there we can invest more in tracking specific actions like registration or joining a community

We can set up analytics for media.livepeer.org, @jozanza brought up question of whether we should be tracking this ethically. @nicolasburtey ' comment on the usefulness is a great idea. What is the balance on this?

**Comment by jozanza** [comment]
Added Google Analytics to [the player](https://github.com/livepeer/livepeerjs/blob/master/packages/player/src/index.js#L43)
