### ISSUE TITLE
Claim not received!

### ISSUE THREAD

**Issue by diogo-alcantara** [livepeer/livepeer-monorepo#481]
**Describe the bug (required)**

Hi, I've done a claim of 2 LPT but received nothing! It says: "You have 0 LPT in your wallet." 

https://etherscan.io/tx/0x0d502f8bfaf2231d7042f8d03f24788106321b57d8c4da9afefd2130c9fd3379

**Expected behavior (required)**

I should receive the amount claimed in my staking wallet.

**To Reproduce (required)**

1. Went to: https://explorer.livepeer.org
2. Claimed Earnings.
3. Approved Metamask Transaction with high GAS.
4. Received none LPT back.

**Device (required):**
 - Device: MacBook Air
 - OS: OSX
 - Browser BRAVE
 - BRAVE Version: 0.68.142 Chromium: 77.0.3865.90 (Official Version) 64 bits
 
**Screenshots (optional)**
![Captura de Tela 2019-10-07 às 23 06 04](https://user-images.githubusercontent.com/31745887/66362646-fb5c4480-e959-11e9-9bb0-6e3a08886fdf.png)
![Captura de Tela 2019-10-07 às 23 11 30](https://user-images.githubusercontent.com/31745887/66362651-ff886200-e959-11e9-82f9-cb2d8f84ed33.png)

**Comment by adamsoffer** [comment]
Claiming LPT will not withdraw rewards into your wallet. To withdraw rewards into your wallet, submit an unstake transaction, wait the 7 day unbonding period, then withdraw them into your wallet.

Side note, manually claiming has been removed from the explorer UI since rewards are automatically claimed and it's no longer necessary.
