### ISSUE TITLE
Stream is taking too long to load on iPhone 5S on 3G

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#49]
When I load the stream

Can we make something in the player which checks:

- the resolution of the viewer's screen

and then use Livepeer to transcode to the right frame size to fit the device.

Also, can we measure:

- the power of the viewer's GPU
- the download bandwidth available from the gateway

and use it to change the bitrate accordingly?

**Comment by chrishobcroft** [comment]
![image-1](https://user-images.githubusercontent.com/2212651/37665741-370467fc-2c5e-11e8-9b03-32f9f33a26b3.jpg)

**Comment by jozanza** [comment]
Yeah, actually, we're using [hls.js](https://github.com/video-dev/hls.js) for playback in the chroma video player on desktop. Once the manifest is parsed, it should log out the different transcoding levels it found and which one it will play ([code here](https://github.com/livepeer/livepeerjs/blob/master/%40livepeer/chroma/src/VideoPlayer/index.js#L383)). hls.js, then automatically adjusts the level depending on the bandwidth available, which it determines from how long the requests for .ts segments are taking.

On a device that natively supports .m3u8 playback, however, I'm less certain about how the playlist selection works. I want to say it also automatically adjusts based on bandwidth, but it'd definitely be worth spending the time to profile all the behavior across different devices, and then to make improvements based on our findings.

At the moment, however, I think the immediate reason why it's taking too long and not selecting a level with a lower bitrate is because our nodes may not actually be transcoding to different profiles properly due to some kind of bug. Having looked at the network traffic for .m3u8 playlists recently in the media player, it looks like there is only a single level available. This could also be some kind of broadcaster node configuration issue. But whatever the reason, if you can help out by confirming or debunking this, that would be super helpful, @chrishobcroft!

**Comment by chrishobcroft** [comment]
So, how can I configure ingest1 to transcode into different formats for me?

I usually stream in 1920x1080 (although sometimes also in 1920x1280, 1620x1080, 1280x720, 1080x1920) so perhaps it can resize the stream, and then through the explorer it can publish the available resized formats.

We can then present these resized formats to the user to select in media.livepeer.org/embed

**Comment by rayj00** [comment]
Would this work?  https://www.w3schools.com/html/html_responsive.asp

**Comment by jozanza** [comment]
@rayj00 That's not quite what's going on here. Although responsive styling would make the video smaller in the viewport, it would still be the same bitrate and consume the same bandwidth. It's more of a matter of making sure the frontend is requesting the right m3u8 manifest and that the manifest contains all of the bitrates levels available so the player knows what bitrates it can select.

**Comment by ericxtang** [comment]
Good discussion here. A lot of players implement their own ABS algorithm.  For example, JWplayer always starts with the lowest bitrate, and tries to switch up higher bitrate if the buffer fills up quickly.  Also good to note that video startup time is one of THE most important metrics people track in the video world - https://mux.com/blog/the-video-startup-time-metric-explained/

**Comment by jozanza** [comment]
Exactly. We use hls.js (and native when support is available), which implements its own ABS algorithm. 

Our current issue is that the m3u8 manifests the player requests only ever seem to contain one level. It's likely being caused by one of the following:

- The manifest being served is missing some transcoded levels
- The jobs being created only have a single 
- The frontend is requesting the original manifest rather than the transcoded manifest

@ericxtang do you have a hunch about which of these is the root of our problem?

**Comment by ericxtang** [comment]
Currently streams in the test network are not being consistently transcoded.  Part of it is due to the fact that a lot of registered transcoders are actually not running.  If the stream doesn't get transcoded, the manifest has only a single bitrate level.  But for the streams that DO get transcoded, we get 3 different bitrates.  In that case, I'm not sure what the frontend is requesting at this point (I would guess the smallest bitrate since one of the core maintainers of hls.js works at JWPlayer).

**Comment by jozanza** [comment]
What I'm seeing is that requests to `https://<STREAM_ROOT_URL>/streams/<MANIFEST_ID>.m3u8` respond with a playlist containing a single bitrate (I haven't actually encountered a playlist with multiple bitrates yet). That url then gets passed as a source to the player, which where an hls.js or native ABS algorithm is applied.

So, on my end, I can do some testing to see if the player applies ABS when playing locally served m3u8 that contains multiple bitrates.

@ericxtang is there a way we can confirm that transcoders are actually transcoding on rinkeby?

**Comment by saskakol** [comment]
+1
Just tried this on my iPhone 5S, and a stream that works fine on desktop does not load regardless of network connection (WiFi or 3G)

**Comment by jozanza** [comment]
I'm going to close this one out in favor of #103
