### ISSUE TITLE
Watch Offchain Streams

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#58]
#### Expected Behavior 

Broadcast nodes make offchain streams available for playback. Would be nice to have the option to view those through the Livepeer player.

#### Current Behavior 

Not possible since it's linked to the Eth address

#### Context 

Some people are frustrated with Rinkeby or can't/dont want to run devenv. They just want to run a local node and see their streams.

#### Possible Solution 

Maybe via query string. Something like `?host=your-host-here-like-localhost&manifestID=manifest-to-playback`

**Comment by jozanza** [comment]
Thanks for bringing this up @j0sh! It's been on the back of my mind to write up some clarification on this for a while.

The explorer is meant to be a user-facing DApp for sharing livestreams. It's not meant to be a developer HLS debugging tool. And since there are already many many pre-existing solutions for debugging HLS playlists, I'd suggest using one of the following approaches as an alternative:

0. Use the old player: https://media.livepeer.org/player.html
0. Use the [`@livepeerjs/chroma`](https://github.com/livepeer/livepeerjs/tree/master/packages/chroma) video player directly without the DApp: [View the Demo](https://vnnyp9v6m0.codesandbox.io/) or [![Edit Livepeer Chroma - Video Player](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnnyp9v6m0)
0. Browse the m3u8 url in Safari since it has native playback. The default local broadcaster url is `http://localhost:8935/stream/<MANIFEST_OR_STREAM_ID>.m3u8`
0. Use that same url in any readily available m3u8 player in any browser. Here are several:
    - https://videojs.github.io/videojs-contrib-hls/
    - https://www.hlsplayer.net/
    - http://hlstester.com/
    - http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html

If we really want a custom developer tool and it can do something none of these other options do already, we can create a new project and figure out the requirements.

But I'd much rather see us include any useful debugging tools directly inside of whatever broadcasting tools/software we distribute. Perhaps even a simple broadcaster cli command that prints out the playlist url could solve a lot of problems for this use case.

>**Edit**: Also if you really want, you can build a version of the player with a custom `REACT_APP_STREAM_ROOT_URL` that can be used for local debugging by following the instructions in the README: https://github.com/livepeer/livepeerjs/tree/master/packages/player#customizing-your-build

**Comment by j0sh** [comment]
I suppose it's a question of discoverability -- the player is going to be the first stop for many broadcasters when they want to test out their stream. We can probably assume a certain level of tech savvy, but broadcasters aren't necessarily developers who know how to work a JS console.

Given the current instability (especially on Rinkeby), we'll have frustrated broadcasters who can't figure out what's wrong, and the burden falls on us to help them diagnose issues. So anything we can do to facilitate that would be a huge help. For example, maybe if we detect 'Broadcaster Offline' , we could show a link saying "Stream not working? Test Locally" that takes them to the old player, populated with localhost and the StreamID etc. That allows the broadcaster to do a little more self-diagnosis before coming to us for help.

**Comment by jozanza** [comment]
I think we can take all the things I just wrote and put them in some document to help broadcasters troubleshoot.

**Comment by jozanza** [comment]
What we are really missing right now is some tools/alerts that tell us whether our network is functioning properly or not. Most people are broadcasting properly afaik, but our ingest/bootnode may have crashed, etc. There's no visibility into that at all. And that particular information could save a lot of headaches and even be useful for us as well.

Less cryptic error messages would go a long way as well. Users are often confused by the console output on the Livepeer node. It'd be good to have an option for some human-readable output to understand problems better.

**Comment by j0sh** [comment]
That's very true, and giving users an easy method to view their own local streams would help in enormously in distinguishing between local issues vs network issues. "The network looks OK to me" isn't really an answer that most users want to hear from us; but if broadcasters can verify their own streams are working locally, that's something they can point to and feel more confident in approaching us about.

If not linking to another local-enabled player, we could at least link to a troubleshooting guide if the player detects that a broadcaster is offline, so broadcasters know where to start looking. Much like tooltips, nudging users towards the "right place" helps a lot and will reduce the frustration when "nothing is working". Especially at this early stage when things are unstable, we're signaling that we recognize things may be imperfect, and that we're trying to help. Empathizes with the user better that way, IMO.
