### ISSUE TITLE
Webhooks MVP: "stream_session_started"

### ISSUE THREAD

**Issue by wohlner** [livepeer/livepeer-monorepo#791]
With the webhooks feature, we add the ability for the video developer's platform to hook into all the different events -- not just if the video is ready, but the progres, and more to be decided. This will make interactivity easier and also allow the video platform to feed in events during ingest and surface them in playback.

**For the MVP of the new webhooks feature, `stream_session_started is the only requirements.**

- These should be triggered when a session starts. 
- At minimum these need to be triggered for all stream ingested via RTMP, if not all streams.
- We can use the Mist Server _triggers_ panel to set up this up. See section 2.5 in the [Mist Server Manual](https://mistserver.org/guides/MistServer_Manual_2.15.pdf).
- If `stream_session_started` gets an error, disallow all sessions for that stream.

**Comment by wohlner** [comment]
**Research to do:** 

Do we have a way to distinguish between the session finishing or disconnecting temporarily? The really quick reconnection case should be easy, same mist server instance. But if reconnecting and hitting a different mist server, do we just start a new session. This is ok but not ideal. Does Mist server have anything that can abstract this and workaround it?

**Comment by wohlner** [comment]
@wohlner docs for this need information about how to query the API to know that the stream has stopped.

**Comment by j0sh** [comment]
> Do we have a way to distinguish between the session finishing or disconnecting temporarily?

If it helps, the node behavior is as following:

* For RTMP, the session is maintained as long as the connection is alive. If there's a disconnect, the session closes.
* For HTTP ingest, there's a one-minute timeout. If no segments are received within a minute, the session is terminated.

Am guessing these webhooks are more for fire-and-forget notifications, rather than a RPC-type where the requester is expected to take an action based on the webhook response (ex. the node's auth webhook). If fire-and-forget, it would be good to also consider the semantics around retries and ordering:

* What's a "successful delivery" ? 200 OK?
* If a notification fails. Should retries be done? How frequently and how often? Is there a limit on retention time or retry attempts?
* Should delivery ordering be maintained? Eg, if the session start notification fails, should the session ended notification be delayed until the start succeeds? (Edit: I realize now that "session ended" has been punted, but it's still worth considering how that might fit later into the overall system.) 
* How to handle a higher volume of notifications. Maybe less of an issue now but worth thinking about as the system scales, since this will be a major integration point for users, and we want to minimize churn there.

One thought to resolve these issues is to batch up notifications if necessary. So rather than a single request per notification, a request could potentially have multiple notifications carried within it. This may mitigate ordering issues and ease load on customer endpoints (eg, maybe we can throttle requests to one per second, and accumulate events in the interim).

**Comment by wohlner** [comment]
@iameli will spec this today. @ya7ya will do an initial implementation this week. @iameli will review and possibly finalize.

**Comment by iameli** [comment]
@ya7ya and me technical spec:

* New schema in schema.yaml: `webhook`
  * Fields:
     * id
     * name - "my favorite webhook"
     * userId
     * timestamp
     * eventType - Right now, required to be `streamStarted`, maybe others later
     * url
     * Not yet: streamId - eventually we might allow users to have multiple "stream groups"
       backed by different webhooks

* New endpoints: `POST /api/webhook`, `GET /api/webhook`, `GET /api/webhook/:id`, `PUT /api/webhook/:id`, `DELETE /api/webhook/id` and for triggering: `POST /api/webhook/trigger` (requires admin access)

Workflow:
* New RTMP connection comes in to Mist, [it triggers the `RTMP_PUSH_REWRITE` action](https://github.com/livepeer/stream-tester/blob/184a76b7ca30c01dee3095c5d28c9cf8a2be5a04/internal/app/mistapiconnector/mistapiconnector_app.go#L223).
* After we successfully retrieve the stream, mist-api-connector should fire `POST /api/webhook/trigger` with a body of {"streamId": "ABC123", eventType: "streamStarted"}
* API server handles that request and looks up all of the webhooks for that streamId and eventType.
* API server fires a JSON body at all user-defined webhooks:
  * Payload:
    * eventType
    * webhookId
    * stream (sanitized, no stream key)

* If we get a HTTP response that is not a 200, return a 400 to mist-api-connector
* If mist-api-connector gets an HTTP response that is not a 200, return an error to Mist

**Comment by darkdarkdragon** [comment]
@ya7ya small note - in RTMP_PUSH_REWRITE mist-api-connector [calls](https://github.com/livepeer/stream-tester/blob/master/internal/app/mistapiconnector/mistapiconnector_app.go#L241) `/stream/manifetId/setactive` endpoint with `Active` param set to true. 
Upon connection close it [calls](https://github.com/livepeer/stream-tester/blob/master/internal/app/mistapiconnector/mistapiconnector_app.go#L172) `/setactive` with false.
I think `/setactive` should be used instead of introducing separate `/api/webhook/trigger` endpoint.
