### ISSUE TITLE
Stream recording and storage MVP

### ISSUE THREAD

**Issue by wohlner** [livepeer/livepeer-monorepo#792]
Record all stream sessions ingested via RTMP and store them.

- .m3u8 with all the ABR renditions
- trigger via webhook, but open to other implementations (please swing ideas by @wohlner)
- CDN playback solution
- .m3u8 playback URL must be different from the livestream .m3u8 playback URL
- one region-agnostic .m3u8 playback URL per stream recording (example URL beginning: https://cdn.livepeer.com/hls/...)

**Comment by wohlner** [comment]
As discussed in the planning meeting today, it is ok if this happens for segment based transcoding too. This could also allow public network users to use this feature, but is definitely not a requirement for the MVP.

**Comment by j0sh** [comment]
It would be good to lean into the node for this, since that benefits all users rather than just the hosted service. We've been testing a recording feature [1][2] but would be interested in learning what else is required to make the node work for this use-case.

[1] https://github.com/livepeer/go-livepeer/commit/5b776565debc43256a1ad235896f89faebd79a86
[2] https://github.com/livepeer/go-livepeer/commit/0b455a18053200c2f6b7e1f5139af5ba4d02328d

**Comment by iameli** [comment]
Agreed completely — I think go-livepeer is the only sensible place for this
to live. I’ll look over the prior work and see if I can get my head around
the full shape of this.

**Comment by iameli** [comment]
Closed in favor of https://github.com/livepeer/go-livepeer/issues/1565 and https://github.com/livepeer/livepeer-infra/issues/139
