### ISSUE TITLE
Provide easy links from explorer.livepeer.org to other complementary Ethereum protocol exploring tools e.g. etherscan, supermax, etc

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#95]
**What's the problem? (required)**

The problem is that I am occasionally exploring Livepeer protocol, and regularly wish to view what e.g. etherscan.io says about a particular address.

**What's the current behavior? (required)**

Current behaviour is that I have to open a new tab, open Etherscan, copy the address from explorer.livepeer.org, paste into the Etherscan, and then press return.

**Do you have any personal experiences dealing with this problem? (optional)**

Many.

**Describe a possible solution you've considered (optional)**

To provide links to "view this account in Etherscan" which open new tab showing the account there.

**Additional context (optional)**

We love livepeerjs and @jozanza

**Comment by jozanza** [comment]
Have you seen the latest update @chrishobcroft ?

**Comment by jozanza** [comment]
I think this one is taken care of since I just added this update to the account page
![screen shot 2018-05-29 at 12 52 43 pm](https://user-images.githubusercontent.com/740794/40673243-3963559a-633f-11e8-9faf-bf09c7f5fc65.png)

This full history actually links to supermax, but the activity on the account page is already using etherscan's API.
